[[redirects]]
  from = "/tracks-proxy"
  to = "https://lindseymariemusic.bandcamp.com"
  status = 200
  force = true

[[headers]]
  for = "/tracks-proxy"
  [headers.values]
  Access-Control-Allow-Origin: *
